"""empty message

Revision ID: 5e71fed43efe
Revises: 8c0891a394e6
Create Date: 2024-04-28 11:08:07.858406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e71fed43efe'
down_revision = '8c0891a394e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_responses', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_responses', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
