"""empty message

Revision ID: 80f65524dfdb
Revises: 5e71fed43efe
Create Date: 2024-04-28 19:18:48.668438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f65524dfdb'
down_revision = '5e71fed43efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requestors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=50), nullable=True))

    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_column('twitter')
        batch_op.drop_column('facebook')
        batch_op.drop_column('instagram')
        batch_op.drop_column('telegram')

    with op.batch_alter_table('requestors', schema=None) as batch_op:
        batch_op.drop_column('twitter')
        batch_op.drop_column('facebook')
        batch_op.drop_column('instagram')
        batch_op.drop_column('telegram')

    # ### end Alembic commands ###
