"""empty message

Revision ID: 8c0891a394e6
Revises: 3da95498ad5d
Create Date: 2024-04-28 11:01:42.690342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0891a394e6'
down_revision = '3da95498ad5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('city_id', existing_type=sa.Integer(), nullable=False)
        batch_op.create_foreign_key(None, 'cities', ['city_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
